baseURL = "http://www.andrewpasic.com/"
languageCode = "en-us"
title = "Andy Pasic"
theme = "hugo-coder"
publishDir = "../www/"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Andrew Pasic"
    description = "Andy Pasic's personal website"
    keywords = "blog,tinkerer,personal"
    info = "Business & Technology Liason"
    avatarurl = "images/avatar.jpg"
    footercontent = "use technology; help people; solve problems;"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []
